@extends('dashboard.layouts.customer.app')
@section('content')
    @include('dashboard.components.customer.navComponent')
    @include('dashboard.components.customer.sidebarComponent')
    @include('dashboard.components.customer.packageDetailsComponent')
    @include('dashboard.components.customer.footerComponent')
    @include('dashboard.components.customer.customerEditComponent')
    @include('dashboard.components.customer.customerPackagepdf')
@endsection